{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "philter.fullname" . }}
  labels:
    {{- include "philter.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.paths }}
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "philter.apiFullname" $ }}
          port: {{ .port | default $.Values.api.service.port }}
          weight: 1
      matches:
        - path:
            type: {{ .type | default "PathPrefix" }}
            value: {{ trimSuffix "/" .path }}/api
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "philter.uiFullname" $ }}
          port: {{ .port | default $.Values.ui.service.port }}
          weight: 1
      matches:
        - path:
            type: {{ .type | default "PathPrefix" }}
            value: {{ trimSuffix "/" .path }}/
  {{- end }}
{{- end }}
