apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "philter.apiFullname" . }}
  labels:
    {{- include "philter.apiLabels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "philter.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.policies.createConfigMap }}
        checksum/policies-json-config: {{ include (print $.Template.BasePath "/philter-api/configmap.yaml") . | sha256sum }}
        {{- end }}

        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "philter.apiLabels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "philter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: philter-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          {{- with .Values.api.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          args:
            - "$JAVA_OPTS"
            {{- with .Values.api.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          {{- with .Values.api.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.policies.createConfigMap }}
            - name: policies
              mountPath: "/opt/philter/policies/"
            {{- end }}

            {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.policies.createConfigMap }}
        - name: policies
          configMap:
            name: {{ include "philter.fullname" . }}-policies
        {{- end }}
        {{- with .Values.api.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.api.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
