apiVersion: v1
kind: Service
metadata:
  name: {{ include "philter.apiFullname" . }}
  labels:
    {{- include "philter.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "philter.apiSelectorLabels" . | nindent 4 }}
