apiVersion: v1
kind: Service
metadata:
  name: {{ include "philter.uiFullname" . }}
  labels:
    {{- include "philter.uiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "philter.uiSelectorLabels" . | nindent 4 }}
